revert on config failure

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -61,3 +61,16 @@ if [ "$(pgrep -c haproxy)" -le 0 ]; then
 else
 	service haproxy restart
 fi
+
+# if configuration fails, revert
+VAL=$(echo $?)
+echo $VAL
+
+if [ "$VAL" -eq 1 ]; then
+	printf "Reverting . . .\n"
+	cp "$HAPROXY_INIT".bak "$HAPROXY_INIT"
+	cp "$HAPROXY_CONFIG".bak "$HAPROXY_CONFIG"
+	print "Done\n"
+else
+	printf "Configuration Successful\n"
+fi
